import type { DocumentControlRole, DocumentPermission } from '@prisma/client'

export const DOCUMENT_ROLE_LABELS: Record<DocumentControlRole, string> = {
  DOCUMENT_VIEWER: 'Consulta de documentos',
  DOCUMENT_AUTHOR: 'Elaborador',
  DOCUMENT_REVIEWER: 'Revisor de conteúdo',
  TECHNICAL_APPROVER: 'Aprovador técnico',
  QUALITY_REVIEWER: 'Revisor da Qualidade',
  DOCUMENT_PUBLISHER: 'Publicador documental',
  DOCUMENT_MANAGER: 'Gestor documental',
  DOCUMENT_AUDITOR: 'Auditor documental',
  EXTERNAL_DOCUMENT_MANAGER: 'Gestor de documentos externos',
}

export const ROLE_DEFAULT_PERMISSIONS: Record<DocumentControlRole, DocumentPermission[]> = {
  DOCUMENT_VIEWER: ['CAN_VIEW_PUBLISHED'],
  DOCUMENT_AUTHOR: ['CAN_VIEW_PUBLISHED', 'CAN_VIEW_SOURCE_FILE', 'CAN_DOWNLOAD_SOURCE_FILE', 'CAN_CREATE_DOCUMENT', 'CAN_CREATE_REVISION', 'CAN_EDIT_DRAFT', 'CAN_SUBMIT_FOR_APPROVAL'],
  DOCUMENT_REVIEWER: ['CAN_VIEW_PUBLISHED', 'CAN_VIEW_SOURCE_FILE', 'CAN_DOWNLOAD_SOURCE_FILE', 'CAN_REVIEW_CONTENT', 'CAN_VIEW_HISTORY'],
  TECHNICAL_APPROVER: ['CAN_VIEW_PUBLISHED', 'CAN_VIEW_SOURCE_FILE', 'CAN_DOWNLOAD_SOURCE_FILE', 'CAN_APPROVE_TECHNICAL', 'CAN_REJECT_TECHNICAL', 'CAN_VIEW_HISTORY'],
  QUALITY_REVIEWER: ['CAN_VIEW_PUBLISHED', 'CAN_VIEW_SOURCE_FILE', 'CAN_DOWNLOAD_SOURCE_FILE', 'CAN_REVIEW_QUALITY', 'CAN_APPROVE_QUALITY', 'CAN_REJECT_QUALITY', 'CAN_VIEW_HISTORY'],
  DOCUMENT_PUBLISHER: ['CAN_VIEW_PUBLISHED', 'CAN_VIEW_SOURCE_FILE', 'CAN_DOWNLOAD_SOURCE_FILE', 'CAN_PUBLISH_DOCUMENT', 'CAN_DIRECT_PUBLISH', 'CAN_VIEW_HISTORY'],
  DOCUMENT_MANAGER: ['CAN_VIEW_PUBLISHED', 'CAN_VIEW_SOURCE_FILE', 'CAN_DOWNLOAD_SOURCE_FILE', 'CAN_VIEW_HISTORICAL_VERSIONS', 'CAN_VIEW_HISTORY', 'CAN_VIEW_FULL_AUDIT', 'CAN_CANCEL_DOCUMENT', 'CAN_INACTIVATE_DOCUMENT', 'CAN_REACTIVATE_DOCUMENT', 'CAN_DELETE_POSTING_ERROR', 'CAN_MANAGE_DOCUMENT_TYPES', 'CAN_MANAGE_APPROVAL_FLOWS', 'CAN_MANAGE_APPROVERS', 'CAN_MANAGE_DOCUMENT_ROLES', 'CAN_EXPORT_DOCUMENT_REPORTS', 'CAN_VIEW_DOCUMENT_METRICS', 'CAN_MANAGE_VALIDITY_RULES', 'CAN_MANAGE_NOTIFICATIONS'],
  DOCUMENT_AUDITOR: ['CAN_VIEW_PUBLISHED', 'CAN_VIEW_SOURCE_FILE', 'CAN_DOWNLOAD_SOURCE_FILE', 'CAN_VIEW_HISTORICAL_VERSIONS', 'CAN_VIEW_HISTORY', 'CAN_VIEW_FULL_AUDIT', 'CAN_RUN_DOCUMENT_AUDITS', 'CAN_EXPORT_DOCUMENT_REPORTS'],
  EXTERNAL_DOCUMENT_MANAGER: ['CAN_VIEW_PUBLISHED', 'CAN_MANAGE_EXTERNAL_DOCUMENTS', 'CAN_VIEW_HISTORY'],
}
