import { Action } from '@prisma/client'

export const MODULE_KEYS = {
  SOLICITACOES: 'solicitacoes',
  CONFIGURACOES: 'configuracoes',
  FROTAS: 'gestao-de-frotas',
  RECUSA: 'direito-de-recusa',
  EQUIPAMENTOS_TI: 'controle-equipamentos-ti',
  CELULAR: 'celular',
  MEUS_DOCUMENTOS: 'meus-documentos',
} as const

export const FEATURE_KEYS = {
  CONFIGURACOES: {
    PAINEL: 'CONFIGURACOES.PAINEL',
    USUARIOS: 'CONFIGURACOES.USUARIOS',
    PERMISSOES: 'CONFIGURACOES.PERMISSOES',
    CENTROS_DE_CUSTO: 'CONFIGURACOES.CENTROS_DE_CUSTO',
    CARGOS: 'CONFIGURACOES.CARGOS',
  },
  SOLICITACOES: {
    ENVIADAS: 'SOLICITACOES.ENVIADAS',
    RECEBIDAS: 'SOLICITACOES.RECEBIDAS',
    APROVACAO: 'SOLICITACOES.APROVACAO',
    CADASTROS: 'SOLICITACOES.CADASTROS',
  },
  FROTAS: {
    VEICULOS: 'FROTAS.VEICULOS',
    CHECKINS: 'FROTAS.CHECKINS',
    DESLOCAMENTO_CHECKIN: 'FROTAS.DESLOCAMENTO_CHECKIN',
    DESLOCAMENTO_PAINEL: 'FROTAS.DESLOCAMENTO_PAINEL',
  },
  RECUSA: {
    PAINEL: 'RECUSA.PAINEL',
    MINHAS: 'RECUSA.MINHAS',
    NOVA: 'RECUSA.NOVA',
    PENDENTES: 'RECUSA.PENDENTES',
  },
  MEUS_DOCUMENTOS: {
    LISTAR: 'MEUS_DOCUMENTOS.LISTAR',
    VISUALIZAR: 'MEUS_DOCUMENTOS.VISUALIZAR',
    ASSINAR: 'MEUS_DOCUMENTOS.ASSINAR',
  },
  EQUIPAMENTOS_TI: {
    ATALHO: 'EQUIPAMENTOS_TI.ATALHO',
    LINHA_TELEFONICA: 'EQUIPAMENTOS_TI.LINHA_TELEFONICA',
    SMARTPHONE: 'EQUIPAMENTOS_TI.SMARTPHONE',
    NOTEBOOK: 'EQUIPAMENTOS_TI.NOTEBOOK',
    DESKTOP: 'EQUIPAMENTOS_TI.DESKTOP',
    MONITOR: 'EQUIPAMENTOS_TI.MONITOR',
    IMPRESSORA: 'EQUIPAMENTOS_TI.IMPRESSORA',
    TPLINK: 'EQUIPAMENTOS_TI.TPLINK',
    OUTROS: 'EQUIPAMENTOS_TI.OUTROS',
  },
} as const

export const ALL_ACTIONS: Action[] = ['VIEW', 'CREATE', 'UPDATE', 'DELETE', 'APPROVE']