import { Action } from '@prisma/client'

export const MODULE_KEYS = {
  SOLICITACOES: 'solicitacoes',
  CONFIGURACOES: 'configuracoes',
  FROTAS: 'gestao-de-frotas',
  RECUSA: 'direito-de-recusa',
} as const

export const FEATURE_KEYS = {
  CONFIGURACOES: {
    PAINEL: 'CONFIGURACOES.PAINEL',
    USUARIOS: 'CONFIGURACOES.USUARIOS',
    PERMISSOES: 'CONFIGURACOES.PERMISSOES',
    CENTROS_DE_CUSTO: 'CONFIGURACOES.CENTROS_DE_CUSTO',
    CARGOS: 'CONFIGURACOES.CARGOS',
  },
  SOLICITACOES: {
    ENVIADAS: 'SOLICITACOES.ENVIADAS',
    RECEBIDAS: 'SOLICITACOES.RECEBIDAS',
    APROVACAO: 'SOLICITACOES.APROVACAO',
    CADASTROS: 'SOLICITACOES.CADASTROS',
  },
  FROTAS: {
    VEICULOS: 'FROTAS.VEICULOS',
    CHECKINS: 'FROTAS.CHECKINS',
    DESLOCAMENTO_CHECKIN: 'FROTAS.DESLOCAMENTO_CHECKIN',
    DESLOCAMENTO_PAINEL: 'FROTAS.DESLOCAMENTO_PAINEL',
  },
  RECUSA: {
    PAINEL: 'RECUSA.PAINEL',
    MINHAS: 'RECUSA.MINHAS',
    NOVA: 'RECUSA.NOVA',
    PENDENTES: 'RECUSA.PENDENTES',
  },
} as const

export const ALL_ACTIONS: Action[] = ['VIEW', 'CREATE', 'UPDATE', 'DELETE', 'APPROVE']