ALTER TABLE `Solicitation`
  MODIFY `status` ENUM(
    'ABERTA',
    'EM_ATENDIMENTO',
    'AGUARDANDO_APROVACAO',
    'AGUARDANDO_TERMO',
    'AGUARDANDO_AVALIACAO_GESTOR',
    'AGUARDANDO_FINALIZACAO_AVALIACAO',
    'CONCLUIDA',
    'CANCELADA'
  ) NOT NULL DEFAULT 'ABERTA';

ALTER TABLE `TipoSolicitacaoApprover`
  MODIFY `role` ENUM('APPROVER', 'VIEWER', 'FINALIZER') NOT NULL DEFAULT 'APPROVER';