const fs = require('fs')
const assert = require('assert')

const lib = fs.readFileSync('src/lib/iso-documents.ts', 'utf8')
const route = fs.readFileSync('src/app/api/documents/published/route.ts', 'utf8')
const grid = fs.readFileSync('src/components/documents/DocumentsGrid.tsx', 'utf8')

assert(lib.includes('export function normalizeDocumentCodeSearch'), 'existe normalizeDocumentCodeSearch exportado')
assert(lib.includes(".toUpperCase()"), 'normalizacao trata caixa baixa/alta')
assert(lib.includes(".replace(/[^A-Z0-9]/g, '')"), 'normalizacao remove ponto, espaco, hifen, barra e outros separadores')
assert(lib.includes('const rawCode = String(filters.code ?? \'\').trim()'), 'buildVersionWhere usa trim no codigo')
assert(lib.includes('buildDocumentCodeSearchVariants(rawCode)'), 'buildVersionWhere considera variantes de codigo')
assert(lib.includes("rawCode.replace(/\\s+/g, '.')"), 'variante troca espacos por ponto')
assert(lib.includes("rawCode.replace(/\\s+/g, '')"), 'variante remove espacos')
assert(lib.includes("rawCode.replace(/-/g, '.')"), 'variante troca hifen por ponto')
assert(lib.includes("rawCode.replace(/[.\\s\\-/]+/g, '')"), 'variante remove ponto, espaco, hifen e barra')
assert(lib.includes('OR: codeVariants.length ? codeVariants.map'), 'where usa OR para variantes de codigo')
assert(lib.includes('status: filters.status ?? undefined'), 'status continua no where')
assert(route.includes('parsed.filters.status = DocumentVersionStatus.PUBLICADO'), 'status PUBLICADO continua obrigatorio na rota de publicados')
assert(lib.includes('isActive: true'), 'document.isActive continua obrigatorio')
assert(lib.includes('normalizeDocumentCodeSearch(row.document.code).includes(codeNormalized)'), 'fallback compara codigo normalizado em memoria')
assert(route.includes('codeOriginal'), 'debug retorna codeOriginal')
assert(route.includes('codeNormalized'), 'debug retorna codeNormalized')
assert(route.includes('variantsTested'), 'debug retorna variantes testadas')
assert(route.includes('totalEncontrado'), 'debug retorna total encontrado')
assert(grid.includes('const trimmedValue = String(value ?? \'\').trim()'), 'grid envia filtros com trim')

console.log('document-published-code-search-normalization-static ok')
