const assert = require('node:assert/strict')
const fs = require('node:fs')
const source = fs.readFileSync('src/app/api/documents/versions/[versionId]/approve/download/route.ts', 'utf8')
assert.match(source, /\[documents\.approve-download\] failed to prepare final pdf/)
assert.match(source, /errorName:\s*err\?\.name/)
assert.match(source, /errorMessage:\s*err\?\.message/)
assert.match(source, /errorCode:\s*err\?\.code/)
assert.match(source, /DOCUMENT_FINAL_PDF_PREPARE_FAILED/)
assert.match(source, /Não foi possível preparar o PDF final do documento\./)
assert.match(source, /status:\s*422/)
console.log('document-approve-download-route ok')
