const fs = require('node:fs')
const assert = require('node:assert/strict')

const grid = fs.readFileSync('src/components/documents/DocumentsGrid.tsx', 'utf8')
const createRoute = fs.readFileSync('src/app/api/documents/route.ts', 'utf8')
const filename = fs.readFileSync('src/lib/documents/documentDownloadFilename.ts', 'utf8')
const pipeline = fs.readFileSync('src/lib/documents/controlledPdfPipeline.ts', 'utf8')
const packageJson = JSON.parse(fs.readFileSync('package.json', 'utf8'))
const diagnose = fs.readFileSync('scripts/diagnose-document-files.ts', 'utf8')

assert.match(grid, /accept="[^"]*\.xls,[^"]*\.xlsx[^"]*application\/vnd\.ms-excel[^"]*application\/vnd\.openxmlformats-officedocument\.spreadsheetml\.sheet[^"]*"/)
assert.match(grid, /Anexe um arquivo válido: PDF, DOC, DOCX, XLS ou XLSX\./)
assert.match(createRoute, /const shouldFinalizeToPdf = familyRule\.family === 'controlled-pdf'/)
assert.match(createRoute, /if \(shouldFinalizeToPdf\) \{[\s\S]*?finalizeToPublishedPdf\(\{ sourceFileUrl: originalFileUrl, documentCode \}\)[\s\S]*?\}/)
assert.match(createRoute, /Anexe um arquivo válido: PDF, DOC, DOCX, XLS ou XLSX\./)
assert.match(pipeline, /if \(familyRule\.family === 'non-controlled-native'\) \{[\s\S]*?outputBuffer: sourceBuffer[\s\S]*?outputFileName: originalFileName[\s\S]*?convertedToPdf: false[\s\S]*?controlledFlowApplied: false/s)
assert.match(filename, /'application\/vnd\.ms-excel': 'xls'/)
assert.match(filename, /'application\/vnd\.openxmlformats-officedocument\.spreadsheetml\.sheet': 'xlsx'/)
assert.match(filename, /new Set\(\['pdf', 'docx', 'doc', 'xls', 'xlsx'\]\)/)
assert.match(packageJson.scripts['documents:diagnose-file'], /ts-node\/register -r tsconfig-paths\/register scripts\/diagnose-document-files\.ts/)
assert.match(diagnose, /RQ\.196,RQ\.198/)
assert.match(diagnose, /Documento está salvo como PDF\. Para baixar como Excel, é necessário substituir\/republicar o arquivo original em \.xls\/\.xlsx ou excluir por erro de postagem e cadastrar novamente com o arquivo correto\./)

console.log('document-rq-native-excel-static ok')
