const assert = require('node:assert/strict')
const fs = require('node:fs')

const documentsGrid = fs.readFileSync('src/components/documents/DocumentsGrid.tsx', 'utf8')
const visualizacaoClient = fs.readFileSync('src/app/dashboard/controle-documentos/visualizacao/[versionId]/visualizacao-documento-client.tsx', 'utf8')
const impressaoPage = fs.readFileSync('src/app/documentos/impressao/[versionId]/page.tsx', 'utf8')
const impressaoClient = fs.readFileSync('src/app/documentos/impressao/[versionId]/impressao-documento-client.tsx', 'utf8')

assert.doesNotMatch(documentsGrid, /window\.open\(/)
assert.doesNotMatch(visualizacaoClient, /window\.open\(/)
assert.doesNotMatch(impressaoClient, /window\.open\(/)
assert.doesNotMatch(visualizacaoClient, /contentWindow\?\.print\(/)
assert.doesNotMatch(visualizacaoClient, /window\.location\.replace\(/)
assert.match(visualizacaoClient, /\/api\/documents\/versions\/\$\{versionId\}\/controlled/)
assert.match(impressaoClient, /\/api\/documents\/versions\/\$\{versionId\}\/controlled/)
assert.match(impressaoClient, /intent: 'print'/)
assert.match(impressaoClient, /window\.location\.replace\(/)
assert.doesNotMatch(impressaoPage, /dashboard\/controle-documentos\/visualizacao/)

console.log('document-controlled-pipeline-ui-regression ok')