const assert = require('node:assert/strict')
const fs = require('node:fs')

const script = fs.readFileSync('scripts/preflight-document-quality-checklists.ts', 'utf8')
assert.match(script, /roundId IS NULL/)
assert.match(script, /stepId IS NULL/)
assert.match(script, /roundVersionMismatch/)
assert.match(script, /stepRoundMismatch/)
assert.match(script, /stepVersionMismatch/)
assert.match(script, /nonQualityStep/)
assert.match(script, /reviewerWithoutDecision/)
assert.match(script, /duplicatesByStepReviewer/)
assert.match(script, /conflictingDuplicates/)
assert.match(script, /before/)
assert.match(script, /after/)
assert.match(script, /--apply --confirm/)
assert.match(script, /beforeInconsistencyCount/)
assert.match(script, /afterInconsistencyCount/)

const migration = fs.readFileSync('scripts/migrate-document-source-files-to-private-storage.ts', 'utf8')
assert.match(migration, /PRIVATE_READ_BEFORE_DB_UPDATE_FAILED/)
assert.match(migration, /DB_UPDATED_PRIVATE_VALIDATED_BEFORE_PUBLIC_REMOVAL/)
assert.match(migration, /await writeReport/)
assert.match(migration, /rollbackError/)
assert.match(migration, /Object\.assign\(before, current\)/)

const transition = fs.readFileSync('src/lib/documents/documentApprovalTransition.ts', 'utf8')
assert.match(transition, /GET_LOCK/)
assert.match(transition, /RELEASE_LOCK/)
assert.match(transition, /document-approval-step:/)
assert.match(transition, /updateMany\(\{ where: \{ id: decision\.id, status: DocumentApprovalDecisionStatus\.PENDING \}/)

const packageJson = JSON.parse(fs.readFileSync('package.json', 'utf8'))
assert.match(packageJson.scripts.test, /test:documents-sgi/)
assert.match(packageJson.scripts['test:documents-sgi'], /document-quality-checklist-preflight-static/)
assert.ok(packageJson.scripts['document:preflight-checklists'])

console.log('document-quality-checklist-preflight-static ok')

const storage = fs.readFileSync('src/lib/documents/documentStorage.ts', 'utf8')
assert.match(storage, /decodeURIComponent/)
assert.match(storage, /path\.isAbsolute/)
assert.match(storage, /Referência pública inválida/)
assert.match(storage, /startsWith\(`\$\{publicRoot\}\$\{path\.sep\}`\)/)

const grid = fs.readFileSync('src/components/documents/DocumentsGrid.tsx', 'utf8')
assert.match(grid, /intent === 'print'/)
assert.match(grid, /\/documents\/view\/\$\{encodeURIComponent\(versionId\)\}\?intent=print/)
assert.doesNotMatch(grid, /intent === 'view' \|\| intent === 'print'[\s\S]{0,160}disposition=attachment/)
const stageA = fs.readFileSync('prisma/migrations/20260713223000_document_publication_and_checklist_finalize/migration.sql', 'utf8')
assert.doesNotMatch(stageA, /MODIFY `roundId` VARCHAR\(191\) NOT NULL/)
assert.doesNotMatch(stageA, /DocumentQualityChecklist_stepId_reviewerUserId_key[\s\S]*ON `DocumentQualityChecklist`/)
assert.ok(!fs.existsSync('prisma/migrations/20260714010000_document_quality_checklist_constraints_after_preflight/migration.sql'))
