const assert = require('node:assert/strict')
const fs = require('node:fs')

const page = fs.readFileSync('src/app/dashboard/controle-documentos/notificacoes/page.tsx', 'utf8')
const panel = fs.readFileSync('src/app/dashboard/controle-documentos/notificacoes/DocumentNotificationsPanel.tsx', 'utf8')
const sidebar = fs.readFileSync('src/components/layout/Sidebar.tsx', 'utf8')

assert.match(page, /isAdmin/)
assert.match(page, /Acesso negado/)
assert.match(panel, /Central de Notificações de Documentos/)
assert.match(panel, /Mapa do fluxo por tipo documental/)
assert.match(panel, /Destinatários/)
assert.match(panel, /Template/)
assert.match(panel, /Prévia/)
assert.match(panel, /Histórico/)
assert.match(panel, /Alertas de configuração/)
assert.match(panel, /\/api\/documents\/notifications/)
assert.match(panel, /mode: 'preview'/)
assert.match(panel, /mode: 'test'/)
assert.match(panel, /ORIGIN_LABELS/)
assert.match(panel, /Departamento responsável/)
assert.match(panel, /Centro de custo responsável/)
assert.match(panel, /Distribuição/)
assert.match(sidebar, /isAdmin && \(\s*<Link[\s\S]*\/dashboard\/controle-documentos\/notificacoes/)
assert.match(sidebar, /Central de Notificações/)

console.info('document-notification-screen-regression.test.cjs: ok')
