const fs = require('fs')
const assert = require('assert')
const src = fs.readFileSync('src/lib/pdf/uncontrolledCopyWatermark.ts', 'utf8')
assert(src.includes("const WATERMARK_TEXT = 'COPIA CONTROLADA'"), 'texto sem acento mantido')
assert(src.includes('LEGACY_WATERMARK_TEXT'), 'texto legado mantido')
assert(src.includes('maxFontSize = 42'), 'fonte máxima menor')
assert(src.includes('estimatedTextWidth') || src.includes('buildSafeWatermarkGeometry'), 'calcula largura estimada')
assert(!src.includes('const centerX = width * 0.18'), 'não usa posição fixa antiga')
console.log('document-watermark-no-clipping-static ok')
