const assert = require('node:assert')
const fs = require('node:fs')

const schema = fs.readFileSync('prisma/schema.prisma', 'utf8')
assert.match(schema, /CAN_VIEW_SOURCE_FILE/)
assert.match(schema, /CAN_DOWNLOAD_SOURCE_FILE/)
assert.match(schema, /sourceStorageKey\s+String\?/)
assert.match(schema, /sourceOriginalName\s+String\?/)
assert.match(schema, /sourceMimeType\s+String\?/)
assert.match(schema, /sourceSizeBytes\s+BigInt\?/)
assert.match(schema, /sourceSha256\s+String\?/)
assert.match(schema, /model DocumentSourceApproverSnapshot/)
assert.match(schema, /SOURCE_FILE_VIEWED/)
assert.match(schema, /SOURCE_FILE_DOWNLOADED/)

const catalog = fs.readFileSync('src/lib/documents/documentRoleCatalog.ts', 'utf8')
for (const role of ['DOCUMENT_AUTHOR', 'DOCUMENT_REVIEWER', 'TECHNICAL_APPROVER', 'QUALITY_REVIEWER', 'DOCUMENT_PUBLISHER', 'DOCUMENT_MANAGER', 'DOCUMENT_AUDITOR']) {
  const line = catalog.split('\n').find((item) => item.trim().startsWith(`${role}: [`)) || ''
  assert(line.includes('CAN_VIEW_SOURCE_FILE'), `${role} deve visualizar original`)
  assert(line.includes('CAN_DOWNLOAD_SOURCE_FILE'), `${role} deve baixar original`)
}
assert(!(catalog.split('\n').find((item) => item.trim().startsWith('DOCUMENT_VIEWER: [')) || '').includes('CAN_DOWNLOAD_SOURCE_FILE'))

const sourceRoute = fs.readFileSync('src/app/api/documents/versions/[versionId]/source/route.ts', 'utf8')
assert.match(sourceRoute, /requireActiveUser/)
assert.match(sourceRoute, /resolveSourceFileAccess/)
assert.match(sourceRoute, /resolvePrivateDocumentSourcePath/)
assert.match(sourceRoute, /SOURCE_FILE_DOWNLOADED/)
assert.match(sourceRoute, /SOURCE_FILE_VIEWED/)
assert.match(sourceRoute, /Content-Disposition/)
assert.match(sourceRoute, /sourceSha256/)
assert.match(sourceRoute, /sourceSizeBytes/)
assert.match(sourceRoute, /legacy-public-source-fallback-used/)

const createRoute = fs.readFileSync('src/app/api/documents/route.ts', 'utf8')
assert.match(createRoute, /savePrivateDocumentSourceFile/)
assert.doesNotMatch(createRoute, /public', 'uploads', 'documents'/)
assert.match(createRoute, /sourceStorageKey/)
assert.match(createRoute, /sourceSha256/)
assert.match(createRoute, /removePrivateDocumentSourceFile/)

const grid = fs.readFileSync('src/components/documents/DocumentsGrid.tsx', 'utf8')
assert.match(grid, /canDownloadSourceFile/)
assert.match(grid, /Baixar arquivo original/)
assert.match(grid, /Este é o arquivo original de elaboração/)
assert.match(grid, /fetch\(`\/api\/documents\/versions\/\$\{sourceDownload\.row\.versionId\}\/source/)
assert.doesNotMatch(grid, /window\.open\(`\/api\/documents\/versions\/\$\{versionId\}\/source/)
assert.doesNotMatch(grid, /window\.confirm/)

const migrate = fs.readFileSync('scripts/migrate-document-source-files-to-private-storage.ts', 'utf8')
assert.match(migrate, /--apply/)
assert.match(migrate, /reportFile/)
assert.match(migrate, /DRY_RUN/)
assert.match(migrate, /sha256/)
assert.match(migrate, /MIGRATED_AND_PUBLIC_REMOVED/)
assert.doesNotMatch(migrate, /ROLLBACK_DRY_RUN_ONLY/)

const sourceAccess = fs.readFileSync('src/lib/documents/documentSourceAccess.ts', 'utf8')
assert.match(sourceAccess, /sourceApproverSnapshots/)
assert.doesNotMatch(sourceAccess, /approverGroup\.members/)
assert.match(sourceAccess, /canDocumentAuthorAccessSourceFile/)
assert.match(sourceAccess, /assignmentScopeType !== 'GLOBAL'/)
assert.match(sourceAccess, /isTechnicalApproverSourceSnapshotAllowed/)

const snapshot = fs.readFileSync('src/lib/documents/documentApprovalSnapshot.ts', 'utf8')
assert.match(snapshot, /roundNumber/)
assert.doesNotMatch(snapshot, /deleteMany\(\{ where: \{ versionId \} \}\)/)
assert.match(snapshot, /documentSourceApproverSnapshot\.createMany/)

const isoDocuments = fs.readFileSync('src/lib/iso-documents.ts', 'utf8')
const isoSelectBlock = isoDocuments.slice(isoDocuments.indexOf('export const ISO_GRID_SELECT'), isoDocuments.indexOf('export type IsoGridRow'))
assert.doesNotMatch(isoSelectBlock, /sourceStorageKey: true/)
assert.doesNotMatch(isoSelectBlock, /sourceFileUrl: true/)
assert.match(isoDocuments, /sourceFileAvailable/)

assert.match(schema, /metadata\s+Json\?/)
assert.match(schema, /enum DocumentSourceAccessPolicy/)
assert.match(schema, /roundNumber\s+Int\s+@default\(1\)/)
assert.match(schema, /SOURCE_FILE_INTEGRITY_FAILED/)
assert.match(sourceRoute, /SOURCE_FILE_INTEGRITY_FAILED/)
assert.match(sourceRoute, /actualSha256/)
assert.match(sourceRoute, /actualSize/)
assert.match(sourceRoute, /metadata:/)
assert.match(migrate, /privateReadValidated/)
assert.match(migrate, /MANUAL_USING_REPORT_AND_DATABASE_BACKUP/)
assert.match(createRoute, /finally/)
assert.match(createRoute, /sanitizeCreatedDocumentForResponse/)
console.log('document-source-file-access-static ok')
