const assert = require('node:assert')
const fs = require('node:fs')

const schema = fs.readFileSync('prisma/schema.prisma', 'utf8')
assert.match(schema, /model DocumentApprovalRound/)
assert.match(schema, /roundNumber\s+Int/)
assert.match(schema, /startedAt\s+DateTime/)
assert.match(schema, /completedAt\s+DateTime\?/)
assert.match(schema, /model DocumentApprovalStep/)
assert.match(schema, /model DocumentApprovalDecision/)
assert.match(schema, /@@unique\(\[stepId, userId\]\)/)
assert.match(schema, /WAIVED/)
assert.match(schema, /model DocumentQualityChecklist/)
assert.match(schema, /model DocumentSegregationException/)
assert.match(schema, /currentPublishedVersionId\s+String\?\s+@unique/)
assert.doesNotMatch(schema, /@@unique\(\[documentTypeId, order\]\)/)
assert.match(schema, /@@index\(\[documentTypeId, order\]\)/)
assert.match(schema, /DOCUMENT_CANCELLED/)

const transition = fs.readFileSync('src/lib/documents/documentApprovalTransition.ts', 'utf8')
assert.match(transition, /startDocumentApprovalFlow/)
assert.match(transition, /documentApprovalDecision\.createMany/)
assert.match(transition, /new Set\(step\.decisions/)
assert.match(transition, /DocumentApprovalDecisionStatus\.WAIVED/)
assert.match(transition, /approvalRule === 'ANY'/)
assert.match(transition, /approvalRule === 'MINIMUM'/)
assert.match(transition, /Você não pode aprovar tecnicamente um documento elaborado por você/)
assert.match(transition, /createDocumentSourceApproverSnapshotRound\(tx, \{ versionId: input\.versionId, roundNumber/)
assert.doesNotMatch(transition, /deleteMany\(\{ where: \{ versionId/)

const publish = fs.readFileSync('src/lib/documents/publishDocumentVersion.ts', 'utf8')
assert.match(publish, /publishDocumentVersion/)
assert.match(publish, /updateMany\(\{ where: \{ id: input\.versionId, status: DocumentVersionStatus\.AGUARDANDO_PUBLICACAO, isCurrentPublished: false \}/)
assert.match(publish, /currentPublishedVersionId: version\.id/)
assert.match(publish, /SELF_PUBLICATION/)
assert.match(publish, /decidedById !== input\.actorUserId/)
assert.match(publish, /Checklist da Qualidade pendente/)
assert.match(publish, /status: DocumentVersionStatus\.OBSOLETO/)

const createRoute = fs.readFileSync('src/app/api/documents/route.ts', 'utf8')
assert.match(createRoute, /initialStatus = DocumentVersionStatus\.AGUARDANDO_PUBLICACAO/)
assert.match(createRoute, /publishDocumentVersion\(\{ versionId: created\.versions\[0\]\.id/)

const rolesRoute = fs.readFileSync('src/app/api/documents/roles/[id]/route.ts', 'utf8')
assert.match(rolesRoute, /Não é possível inativar o último gestor documental ativo/)
assert.match(rolesRoute, /role: 'DOCUMENT_MANAGER'/)

const legacyScript = fs.readFileSync('scripts/migrate-document-approval-controls.ts', 'utf8')
assert.match(legacyScript, /active: true/)
assert.doesNotMatch(legacyScript, /active: true \} \}\)/)
assert.match(legacyScript, /GLOBAL não é atribuído silenciosamente/)

const cancelRoute = fs.readFileSync('src/app/api/documents/versions/[versionId]/cancel/route.ts', 'utf8')
assert.match(cancelRoute, /DOCUMENT_CANCELLED/)
assert.doesNotMatch(cancelRoute, /sendDocumentNotification\('DOCUMENT_REJECTED'/)

const roleAccess = fs.readFileSync('src/lib/documents/documentRoleAccess.ts', 'utf8')
assert.match(roleAccess, /currentPendingApprovalStep/)
assert.match(roleAccess, /DocumentApprovalRoundStatus\.PENDING/)
assert.match(roleAccess, /DocumentApprovalDecisionStatus\.PENDING/)
assert.doesNotMatch(roleAccess, /approverGroup\.members\.some/)

const checklistRoute = fs.readFileSync('src/app/api/documents/versions/[versionId]/quality-checklist/route.ts', 'utf8')
assert.match(checklistRoute, /roundId/)
assert.match(checklistRoute, /stepId/)
const checklistCompleteRoute = fs.readFileSync('src/app/api/documents/versions/[versionId]/quality-checklist/complete/route.ts', 'utf8')
assert.match(checklistCompleteRoute, /completedAt: new Date\(\)/)

const exceptionsRoute = fs.readFileSync('src/app/api/documents/segregation-exceptions/[id]/approve/route.ts', 'utf8')
assert.match(exceptionsRoute, /requestedById === me\.id/)
assert.match(exceptionsRoute, /Somente outro gestor documental ativo/)

const backfillScript = fs.readFileSync('scripts/migrate-pending-document-approvals-to-rounds.ts', 'utf8')
assert.match(backfillScript, /approvalRounds: \{ none: \{\} \}/)
assert.match(backfillScript, /--apply/)
const auditScript = fs.readFileSync('scripts/audit-current-published-versions.ts', 'utf8')
assert.match(auditScript, /MULTIPLE_CURRENT_PUBLISHED_VERSIONS/)
console.log('document-approval-decisions-static ok')
