const fs = require('fs')
const assert = require('assert')
const helper = fs.readFileSync('src/lib/documents/documentManagementAccess.ts', 'utf8')
const access = fs.readFileSync('src/app/api/documents/management-access/route.ts', 'utf8')
const cancel = fs.readFileSync('src/app/api/documents/versions/[versionId]/cancel/route.ts', 'utf8')
const del = fs.readFileSync('src/app/api/documents/[id]/route.ts', 'utf8')
const grid = fs.readFileSync('src/components/documents/DocumentsGrid.tsx', 'utf8')
assert(access.includes('requireQualityDocumentManager'), 'management-access usa helper')
assert(cancel.includes('requireQualityDocumentManager'), 'cancel route usa helper')
assert(del.includes('requireQualityDocumentManager'), 'delete route usa helper')
assert(grid.includes('canManageDocuments ?'), 'DocumentsGrid condiciona ações')
assert(helper.includes('ModuleLevel.NIVEL_3') && helper.includes('department') && helper.includes('DOCUMENT_QUALITY_MANAGER_EMAILS'), 'NIVEL_3 sozinho não é suficiente')
console.log('document-quality-management-access-static ok')
