const fs = require('fs')
const assert = require('assert')
const script = fs.readFileSync('scripts/diagnose-published-documents-visibility.ts', 'utf8')
assert(script.includes('prisma.isoDocument.findMany'), 'consulta IsoDocument por code')
assert(script.includes('versions:'), 'lista versões')
assert(script.includes('isActive'), 'identifica isActive')
assert(script.includes('DocumentVersionStatus.PUBLICADO'), 'identifica status PUBLICADO')
assert(script.includes('appearsInPublishedGrid'), 'informa se aparece no grid')
console.log('document-published-visibility-diagnostic-static ok')
