const fs = require('fs')
const assert = require('assert')
const script = fs.readFileSync('scripts/audit-published-documents-health.ts', 'utf8')
assert(script.includes("process.argv.includes('--all')"), 'aceita --all')
assert(script.includes("startsWith('--codes=')"), 'aceita --codes')
assert(script.includes('prisma.isoDocument.findMany'), 'usa prisma.isoDocument.findMany')
assert(script.includes('isActive'), 'verifica isActive')
assert(script.includes('DocumentVersionStatus.PUBLICADO'), 'verifica PUBLICADO')
assert(script.includes('isCurrentPublished'), 'verifica isCurrentPublished')
assert(script.includes('fileUrl'), 'verifica fileUrl')
assert(script.includes('resolvePublicDocumentPath'), 'usa resolvePublicDocumentPath')
assert(script.includes('validatePdfBuffer'), 'usa validatePdfBuffer')
assert(script.includes("logs', 'document-health-audit.json"), 'grava logs/document-health-audit.json')
assert.doesNotMatch(script, /\.\s*(update|create|delete|upsert)\s*\(/, 'nao usa update/create/delete/upsert')
console.log('document-health-audit-static ok')
