const fs = require('fs')
const assert = require('assert')
const stamp = fs.readFileSync('src/lib/pdf/documentHeaderStamp.ts', 'utf8')
const finalize = fs.readFileSync('src/lib/documents/finalizeToPublishedPdf.ts', 'utf8')
const pipeline = fs.readFileSync('src/lib/documents/controlledPdfPipeline.ts', 'utf8')
assert(stamp.includes('applyDocumentCornerRevisionStamp'), 'função existe')
assert(stamp.includes('| Rev.') && stamp.includes('documentCode'), 'aplica texto com código e revisão')
assert(stamp.includes('for (const pageObject of pageObjects)'), 'aplica em todas as páginas')
assert(stamp.includes('hasDocumentCornerRevisionStamp') && stamp.includes('DOC_REV_STAMP'), 'não duplica')
assert(finalize.includes('validatePdfBuffer') && pipeline.includes('validatePdf'), 'validatePdfBuffer retorna válido nos fluxos')
console.log('document-revision-corner-stamp ok')
