const assert = require('node:assert')
const fs = require('node:fs')
const pkg = require('../package.json')
const diagnose = fs.readFileSync('scripts/diagnose-epi-approval-flow.ts', 'utf8')
const fix = fs.readFileSync('scripts/fix-epi-attachments-and-approval.ts', 'utf8')
assert(pkg.scripts['epi:diagnose'].includes('ts-node/register') && pkg.scripts['epi:diagnose'].includes('scripts/diagnose-epi-approval-flow.ts'), 'epi:diagnose deve registrar ts-node com suporte a paths')
assert(pkg.scripts['epi:fix'].includes('ts-node/register') && pkg.scripts['epi:fix'].includes('scripts/fix-epi-attachments-and-approval.ts'), 'epi:fix deve registrar ts-node com suporte a paths')
for (const text of ['user-email', 'since', 'tipo', 'protocolo', 'requiresApproval', 'approvalStatus', 'approverId', 'anexos existentes', 'aparece em Recebidas?', 'aparece em Aprovações?', 'motivo de não aparecer em Aprovações', 'ação recomendada']) assert(diagnose.includes(text), `diagnóstico deve imprimir ${text}`)
assert(fix.includes('apply = process.argv.includes') && fix.includes('normalizeStoredAttachmentUrl') && fix.includes('isEpiUniformeReadyToForwardApproval'), 'fix deve simular/aplicar normalização e encaminhamento EPI')
for (const text of ['assertCanMoveEpiUniformeToSst(moveToSst, protocols)', 'resolveSstDepartmentAndCostCenter', "externalCode: '580'", 'buildEpiUniformeMoveToSstData', 'centro 580']) assert(fix.includes(text), `fix deve conter ${text}`)
console.log('epi-admin-scripts-static ok')
