const assert = require('node:assert')
const fs = require('node:fs')
const pkg = require('../package.json')
const diagnose = fs.readFileSync('scripts/diagnose-epi-approval-flow.ts', 'utf8')
const fix = fs.readFileSync('scripts/fix-epi-attachments-and-approval.ts', 'utf8')
assert.equal(pkg.scripts['epi:diagnose'], 'ts-node -r tsconfig-paths/register scripts/diagnose-epi-approval-flow.ts')
assert.equal(pkg.scripts['epi:fix'], 'ts-node -r tsconfig-paths/register scripts/fix-epi-attachments-and-approval.ts')
for (const text of ['protocolo', 'requiresApproval', 'approvalStatus', 'approverId', 'aparece em Recebidas?', 'aparece em Aprovações?', 'motivo de não aparecer em Aprovações']) assert(diagnose.includes(text), `diagnóstico deve imprimir ${text}`)
assert(fix.includes('apply = process.argv.includes') && fix.includes('normalizeStoredAttachmentUrl') && fix.includes('isEpiUniformeReadyToForwardApproval'), 'fix deve simular/aplicar normalização e encaminhamento EPI')
console.log('epi-admin-scripts-static ok')
