const assert = require('node:assert')
const fs = require('node:fs')

const listRoute = fs.readFileSync('src/app/api/solicitacoes/route.ts', 'utf8')
const anexosRoute = fs.readFileSync('src/app/api/solicitacoes/[id]/anexos/route.ts', 'utf8')
const approveRoute = fs.readFileSync('src/app/api/solicitacoes/[id]/aprovar/route.ts', 'utf8')
const rejectRoute = fs.readFileSync('src/app/api/solicitacoes/[id]/reprovar/route.ts', 'utf8')
const flow = fs.readFileSync('src/lib/epiUniformeFlow.ts', 'utf8')
const approvalsPage = fs.readFileSync('src/app/dashboard/solicitacoes/aprovacao/page.tsx', 'utf8')
const detailRoute = fs.readFileSync('src/app/api/solicitacoes/[id]/route.ts', 'utf8')
const modal = fs.readFileSync('src/components/solicitacoes/SolicitationDetailModal.tsx', 'utf8')

assert(flow.includes('isEpiUniformeApprovalPending'), 'deve existir função central de pendência de aprovação EPI')
assert(flow.includes('Aguardando SST anexar Ficha de EPI'), 'deve haver label para recebidas antes da ficha')
assert(flow.includes('Aguardando encaminhamento para aprovação'), 'deve haver label para recebidas após ficha')
assert(listRoute.includes("scope === 'to-approve'"), 'lista deve tratar aba Aprovações')
assert(listRoute.includes('where.requiresApproval = true') && listRoute.includes("where.approvalStatus = 'PENDENTE'"), 'Aprovações filtra pendentes')
assert(listRoute.includes('TipoApproverRole.APPROVER'), 'Aprovações considera aprovador configurado do tipo')
assert(listRoute.includes('approverId: me.id'), 'Aprovações considera approverId')
assert(listRoute.includes('getEpiUniformeReceivedResponsibilityLabel'), 'Recebidas deve exibir responsável amigável para EPI')
assert(anexosRoute.includes('isEpiUniformeReadyToForwardApproval'), 'anexo deve encaminhar EPI elegível para aprovação')
assert(anexosRoute.includes("requiresApproval: true") && anexosRoute.includes("approvalStatus: 'PENDENTE'") && anexosRoute.includes("status: 'AGUARDANDO_APROVACAO'"), 'anexo de ficha deve mudar para aprovação pendente')
assert(approveRoute.includes('Solicitação de EPI aprovada e encaminhada'), 'aprovação EPI deve registrar timeline de encaminhamento')
assert(rejectRoute.includes("approvalStatus: 'REPROVADO'") && rejectRoute.includes("status: 'CANCELADA'"), 'reprovação EPI deve sair da fila')
assert(approvalsPage.includes('/api/solicitacoes?scope=to-approve'), 'aba Aprovações deve consumir scope=to-approve')
assert(detailRoute.includes('canApproveByRule'), 'detalhe deve devolver permissão de aprovação compatível com a lista')
assert(detailRoute.includes('approverId === me.id'), 'detalhe deve considerar approverId')
assert(detailRoute.includes('tipoApproverTipoIds'), 'detalhe deve considerar aprovador configurado do tipo')
assert(detailRoute.includes('ModuleLevel.NIVEL_3'), 'detalhe deve considerar nível 3 autorizado por departamento')
assert(modal.includes('canApproveByCompatibleRule'), 'modal deve usar regra compatível de aprovação')
assert(!modal.includes('canApproveEpiUniforme'), 'modal não deve esconder botão de EPI com regra diferente da lista')
console.log('epi-approval-flow-static ok')
