require('ts-node/register')
require('tsconfig-paths/register')
const assert = require('node:assert')
const fs = require('node:fs')
const { normalizeStoredAttachmentUrl } = require('../src/lib/files/attachmentStorage')

assert.equal(normalizeStoredAttachmentUrl('/upload/documents/a.pdf'), '/uploads/documents/a.pdf')
assert.equal(normalizeStoredAttachmentUrl('/uploads/documents/a.pdf'), '/uploads/documents/a.pdf')

const uploadRoute = fs.readFileSync('src/app/api/solicitacoes/[id]/anexos/route.ts', 'utf8')
const detailRoute = fs.readFileSync('src/app/api/solicitacoes/[id]/route.ts', 'utf8')
const downloadRoute = fs.readFileSync('src/lib/solicitationAttachmentDownload.ts', 'utf8')
const downloadAlias = fs.readFileSync('src/app/api/solicitacoes/[id]/anexos/[anexoId]/download/route.ts', 'utf8')
const modal = fs.readFileSync('src/components/solicitacoes/SolicitationDetailModal.tsx', 'utf8')
const storage = fs.readFileSync('src/lib/files/attachmentStorage.ts', 'utf8')

assert(uploadRoute.includes('buildDocumentUploadPaths'), 'upload novo deve usar storage central')
assert(storage.includes("/uploads/documents/"), 'storage novo deve usar /uploads/documents')
assert(detailRoute.includes('downloadUrl: `/api/solicitacoes/${item.id}/anexos/${a.id}/download`'), 'detalhe deve retornar downloadUrl protegido')
assert(downloadRoute.includes('buildSolicitationVisibilityContext') && downloadRoute.includes('canUserViewSolicitationByFallback'), 'download deve validar permissão de visualização')
assert(downloadRoute.includes('resolveExistingAttachmentPath'), 'download deve resolver paths antigos e novos')
assert(downloadRoute.includes('Arquivo não encontrado no servidor. Reenvie o anexo ou acione o suporte.'), 'download deve retornar erro claro')
assert(downloadAlias.includes('downloadSolicitationAttachment'), 'rota /download deve reutilizar handler protegido')
assert(modal.includes('a.downloadUrl ??'), 'modal deve priorizar downloadUrl')
console.log('epi-attachment-download-static ok')
