const assert = require('node:assert/strict')
const fs = require('node:fs')

const notificationLib = fs.readFileSync('src/lib/sst/nonConformityNotifications.ts', 'utf8')
assert.match(notificationLib, /resolveNonConformityQualityRecipients/)
assert.match(notificationLib, /resolveNonConformityInvolvedAreaRecipients/)
assert.match(notificationLib, /resolveNonConformityRequesterRecipients/)
assert.match(notificationLib, /resolveActionPlanResponsibleRecipients/)
assert.match(notificationLib, /resolveNonConformityNotificationRecipientsByEvent/)
assert.match(notificationLib, /NC_CREATED/)
assert.match(notificationLib, /NC_APPROVED_BY_QUALITY/)
assert.match(notificationLib, /ACTION_ITEM_ASSIGNED/)
assert.match(notificationLib, /Falha no envio de alerta de NC/)

console.log('non-conformity-alert-recipients ok')
