const fs = require('fs')
const assert = require('assert')

const route = fs.readFileSync('src/app/api/sst/nao-conformidades/[id]/estudo-causa/route.ts', 'utf8')
const detailRoute = fs.readFileSync('src/app/api/sst/nao-conformidades/[id]/route.ts', 'utf8')
const client = fs.readFileSync('src/app/dashboard/sst/nao-conformidades/[id]/NaoConformidadeDetailClient.tsx', 'utf8')
const schema = fs.readFileSync('prisma/schema.prisma', 'utf8')

assert.doesNotMatch(route, /assertCanFeature\([^\n]+ESTUDO_DE_CAUSA/, 'salvar estudo de causa não deve exigir feature específica')
assert.doesNotMatch(route, /canUserAccessNc\(/, 'salvar estudo de causa não deve usar regra global de acesso da RNC')
assert.doesNotMatch(route, /getUserCostCenterIds\(me\.id\)/, 'salvar estudo de causa não deve bloquear nível 1 por centro de custo')
assert.match(route, /hasMinLevel\(effectiveLevel, ModuleLevel\.NIVEL_1\)/, 'salvar deve exigir nível mínimo 1 no módulo SST/SGI Qualidade')
assert.match(route, /canFeature\(me\.id, MODULE_KEYS\.SST, FEATURE_KEYS\.SST\.NAO_CONFORMIDADES, Action\.VIEW\)/, 'salvar deve validar visualização/acesso básico a Não Conformidades')
assert.match(route, /status === 'CANCELADA' \|\| nc\.status === 'ENCERRADA'/, 'status finais devem bloquear edição')
assert.match(route, /nonConformityCauseStudyEditLog\.create/, 'edição deve gerar log detalhado')
assert.match(route, /actorId:\s*me\.id/, 'log deve persistir actorId')
assert.match(route, /actorName:\s*me\.fullName/, 'log deve persistir actorName')
assert.match(route, /actorLogin:\s*me\.login/, 'log deve persistir actorLogin')
assert.match(route, /actorEmail:\s*me\.email/, 'log deve persistir actorEmail')
assert.match(schema, /editedAt\s+DateTime\s+@default\(now\(\)\)/, 'log deve registrar editedAt automaticamente')
assert.match(route, /changes,/, 'log deve persistir lista de mudanças')
assert.match(route, /Campos alterados: \$\{changes\.length\}/, 'timeline deve receber mensagem curta com contagem')
assert.doesNotMatch(route, /message:\s*JSON\.stringify/, 'timeline não deve gravar JSON grande em message')
assert.match(detailRoute, /estudoCausaEditLogs:\s*\{[\s\S]*changes:\s*true/, 'GET da RNC deve retornar logs detalhados')
assert.match(schema, /model NonConformityCauseStudyEditLog/, 'schema deve declarar tabela própria de histórico')
assert.match(client, /Histórico de edições/, 'frontend deve oferecer botão/área de histórico')
assert.match(client, /Nenhuma edição registrada\./, 'frontend deve tratar ausência de logs')
assert.match(client, /const estudoCausaBloqueado = item\?\.status === 'CANCELADA' \|\| item\?\.status === 'ENCERRADA'/, 'frontend deve bloquear somente status finais para estudo de causa')
assert.doesNotMatch(client, /Sem permissão para editar estudo de causa/, 'frontend não deve exibir bloqueio preventivo por feature')

console.info('nonconformity-cause-study-access-and-history-regression.test.cjs: ok')
