const fs = require('fs')
const assert = require('assert')

const route = fs.readFileSync('src/app/api/sst/nao-conformidades/[id]/estudo-causa/route.ts', 'utf8')
const detailRoute = fs.readFileSync('src/app/api/sst/nao-conformidades/[id]/route.ts', 'utf8')
const client = fs.readFileSync('src/app/dashboard/sst/nao-conformidades/[id]/NaoConformidadeDetailClient.tsx', 'utf8')
const schema = fs.readFileSync('prisma/schema.prisma', 'utf8')

assert.doesNotMatch(route, /assertCanFeature\([^\n]+ESTUDO_DE_CAUSA/, 'salvar estudo de causa não deve exigir feature específica')
assert.match(route, /canUserAccessNc\(/, 'salvar deve autorizar pelo acesso à própria RNC')
assert.match(route, /getUserCostCenterIds\(me\.id\)/, 'salvar deve considerar centros de custo do usuário')
assert.match(route, /status === 'CANCELADA' \|\| nc\.status === 'ENCERRADA'/, 'status finais devem bloquear edição')
assert.match(route, /nonConformityCauseStudyEditLog\.create/, 'edição deve gerar log detalhado')
assert.match(route, /changes,/, 'log deve persistir lista de mudanças')
assert.match(route, /Campos alterados: \$\{changes\.length\}/, 'timeline deve receber mensagem curta com contagem')
assert.doesNotMatch(route, /message:\s*JSON\.stringify/, 'timeline não deve gravar JSON grande em message')
assert.match(detailRoute, /estudoCausaEditLogs:\s*\{[\s\S]*changes:\s*true/, 'GET da RNC deve retornar logs detalhados')
assert.match(schema, /model NonConformityCauseStudyEditLog/, 'schema deve declarar tabela própria de histórico')
assert.match(client, /Histórico de edições/, 'frontend deve oferecer botão/área de histórico')
assert.match(client, /Nenhuma edição registrada\./, 'frontend deve tratar ausência de logs')
assert.match(client, /const estudoCausaBloqueado = item\?\.status === 'CANCELADA' \|\| item\?\.status === 'ENCERRADA'/, 'frontend deve bloquear somente status finais para estudo de causa')
assert.doesNotMatch(client, /Sem permissão para editar estudo de causa/, 'frontend não deve exibir bloqueio preventivo por feature')

console.info('nonconformity-cause-study-access-and-history-regression.test.cjs: ok')
