const assert = require('assert'); const fs = require('fs');
const page = fs.readFileSync('src/app/dashboard/solicitacoes/enviadas/nova/page.tsx','utf8');
assert(page.includes('handleCargoChange'));
assert(page.includes('indexadorCargo'));
assert(page.includes('documentoCargoId'));
assert(page.includes('Este cargo não possui documento oficial anexado.'));
assert(page.includes('Cargo cadastrado'), 'RQ_063 deve rotular a seleção obrigatória como Cargo cadastrado');
assert(page.includes('Selecione um cargo cadastrado antes de enviar a solicitação.'), 'RQ_063 deve bloquear envio sem cargoId');
assert(page.includes('Regularize o cadastro antes de prosseguir.'), 'RQ_063 deve bloquear cargo sem documento oficial');
assert(page.includes('cargoId: cargoId || extras.cargoId'), 'payload deve gravar cargoId vindo do cadastro');
assert(!page.includes("cargo: extras.cargo ?? ''"), 'RQ_063 não deve enviar cargo manual em vez de cargo cadastrado');
assert(page.includes('filteredPositionsForRq063'), 'RQ_063 deve filtrar cargos por busca/autocomplete');
assert(page.includes('Pesquise por nome, indexador, CBO ou área/setor'), 'RQ_063 deve oferecer busca por nome, indexador, CBO ou área/setor');
assert(page.includes('value={abonoCampos.cargo'), 'Abono deve manter cargo como input manual próprio do fluxo');
console.log('position-rq063-prefill ok');
