const assert = require('assert'); const fs = require('fs');
const preview = fs.readFileSync('src/app/api/positions/document-preview/route.ts','utf8');
const upload = fs.readFileSync('src/app/api/positions/[id]/documents/route.ts','utf8');
const route = fs.readFileSync('src/app/api/positions/route.ts','utf8');
const byId = fs.readFileSync('src/app/api/positions/[id]/route.ts','utf8');
const modal = fs.readFileSync('src/app/dashboard/configuracoes/cargos/CargoFormModal.tsx','utf8');
const schema = fs.readFileSync('prisma/schema.prisma','utf8');
const download = fs.readFileSync('src/app/api/positions/[id]/documents/[documentId]/download/route.ts','utf8');
assert(preview.includes('createPositionDocumentPreview'));
assert(!preview.includes('positionDocument.create'), 'preview não deve criar PositionDocument definitivo');
assert(upload.includes('attachPreviewedPositionDocument'));
assert(route.includes('attachPreviewedPositionDocument'), 'salvar cargo novo com tempFileToken deve anexar documento');
assert(byId.includes('attachPreviewedPositionDocument'), 'salvar cargo existente com tempFileToken deve anexar/substituir documento');
assert(modal.includes('/api/positions/document-preview'), 'cargo novo pode ser preenchido pelo documento antes de salvar');
assert(modal.includes('/documents/${currentDocument.id}/download'), 'download deve usar rota protegida');
assert(download.includes('requireActiveUser'), 'download de documento de cargo deve exigir usuário autenticado');
assert(download.includes('status: 403'), 'download de documento de cargo deve bloquear usuário sem permissão');
assert(download.includes('moduleLevels?.configuracoes'), 'download deve permitir Configurações nível 3 além de RH/admin');
assert(schema.includes('model PositionDocument'));
console.log('position-document-upload-static ok');
