const assert = require('assert'); const fs = require('fs');
const page = fs.readFileSync('src/app/dashboard/solicitacoes/enviadas/nova/page.tsx','utf8');
assert(page.includes('Informe o cargo solicitado'), 'RQ_063 deve orientar cargo manual com mensagem correta');
assert(page.includes("setSubmitError('Informe o cargo solicitado.')"), 'RQ_063 deve validar cargo texto livre');
assert(page.includes("cargo: extras.cargoNome ?? extras.cargo ?? ''"), 'RQ_063 deve enviar cargo manual no payload');
assert(page.includes("cargoId: extras.cargoId ?? ''"), 'payload mantém cargoId apenas por compatibilidade quando já existir');
assert(!page.includes('Selecione um cargo cadastrado antes de enviar a solicitação.'), 'RQ_063 não deve bloquear envio sem cargoId');
assert(!page.includes('Cargo cadastrado'), 'RQ_063 não deve rotular o cargo como cadastro obrigatório');
assert(!page.includes('Regularize o cadastro antes de prosseguir.'), 'RQ_063 não deve exigir documento oficial do cargo');
assert(!page.includes("fetch('/api/positions?pageSize=200')"), 'RQ_063 não deve carregar /api/positions como dependência do envio');
assert(!page.includes('filteredPositionsForRq063'), 'RQ_063 não deve depender de autocomplete de cargos cadastrados');
assert(page.includes('value={abonoCampos.cargo'), 'Abono deve manter cargo como input manual próprio do fluxo');
console.log('position-rq063-prefill ok');
