const fs = require('fs')
const assert = require('assert')
const read = (p) => fs.readFileSync(p, 'utf8')
const schema = read('prisma/schema.prisma')
const migration = read('prisma/migrations/202607070001_quality_action_plan_hierarchy/migration.sql')
const client = read('src/app/dashboard/sst/planos-de-acao/PlanosDeAcaoClient.tsx')
const detail = read('src/app/dashboard/sst/planos-de-acao/[planId]/PlanoAvulsoDetailClient.tsx')
const actionDetail = read('src/app/dashboard/sst/planos-de-acao/[planId]/acoes/[actionId]/AcaoPlanoAvulsoDetailClient.tsx')
const actionPage = read('src/app/dashboard/sst/planos-de-acao/[planId]/acoes/[actionId]/page.tsx')
const sgiActionPage = read('src/app/dashboard/sgi/qualidade/planos-de-acao/[planId]/acoes/[actionId]/page.tsx')
const page = read('src/app/dashboard/sst/planos-de-acao/[planId]/page.tsx')
const menu = read('src/components/layout/Sidebar.tsx')
const actionListRoute = read('src/app/api/sst/planos-de-acao/[planId]/acoes/route.ts')
const actionItemRoute = read('src/app/api/sst/planos-de-acao/[planId]/acoes/[actionId]/route.ts')
const ncRoute = read('src/app/api/sst/nao-conformidades/[id]/plano-de-acao/route.ts')
assert.match(schema, /model QualityActionPlan\s*\{/)
assert.match(schema, /model QualityActionPlanSequence\s*\{/)
assert.match(schema, /enum QualityActionPlanStatus\s*\{/)
assert.match(schema, /qualityActionPlanId\s+String\?/)
assert.match(schema, /nonConformityId\s+String\?/)
assert.match(migration, /GROUP BY `groupKey`, `numeroPlano`/, 'migração deve agrupar legados por referência')
assert.match(migration, /UPDATE `NonConformityActionItem` ai[\s\S]*qualityActionPlanId/, 'migração deve vincular ações ao plano pai')
assert.match(client, /Registrar plano de ação/)
assert.match(client, /Título \*/)
assert.match(client, /Responsável/)
const modalBlock = client.slice(client.indexOf('Registrar plano de ação', client.indexOf('modalOpen')))
assert.doesNotMatch(modalBlock, /<Field label="Origem"|<Field label="Referência"|<Field label="Início previsto"|<Field label="Fim previsto"|<Field label="Investimento"|<Field label="Objetivo"|<Field label="Resultado esperado"/)
assert.match(client, /fetch\('\/api\/sst\/planos-de-acao'/)
assert.match(client, /fetch\(`\/api\/sst\/planos-de-acao\/\$\{planId\}\/acoes`/)
assert.match(client, /router\.push\(`\/dashboard\/sgi\/qualidade\/planos-de-acao\/\$\{planId\}\/acoes\/\$\{actionId\}`\)/)
assert.match(menu, /Não conformidades/)
assert.match(menu, /Planos de ação avulsos/)
assert.doesNotMatch(menu, /Ações da não conformidade|Registrar plano de ação|Ações do plano de ação|NÃO CONFORMIDADE|PLANOS DE AÇÕES/)
assert.match(actionDetail, /export default function AcaoPlanoAvulsoDetailClient/)
assert.match(actionDetail, /Ação - Dados Básicos/)
assert.match(actionDetail, /Evidências/)
;['O quê?', 'Por quê?', 'Como?', 'Onde?', 'Centro Responsável', 'Quem?', 'Início previsto', 'Fim previsto', 'Quanto? (custo)', 'Data Conclusão', 'Tipo', 'Origem', 'Referência', 'Status', 'RAB'].forEach((label) => assert.match(actionDetail, new RegExp(label.replace(/[()?]/g, '\\$&'))))
assert.match(actionDetail, /Voltar para ações do plano/)
assert.doesNotMatch(actionDetail, /\/anexos|Upload de anexos|Adicionar Observações|timeline:\s*\[\]/)
assert.doesNotMatch(actionItemRoute, /timeline:\s*\[\]/)
assert.match(actionPage, /AcaoPlanoAvulsoDetailClient/)
assert.match(sgiActionPage, /AcaoPlanoAvulsoDetailClient/)
assert.doesNotMatch(detail, /ActionModal|actionModalOpen|setActionModalOpen/)
assert.match(detail, /Nova ação/)
assert.match(detail, /fetch\(`\/api\/sst\/planos-de-acao\/\$\{planId\}\/acoes`/)
assert.match(detail, /router\.push\(`\/dashboard\/sgi\/qualidade\/planos-de-acao\/\$\{planId\}\/acoes\/\$\{action\.id\}`\)/)
assert.match(detail, /Exibir\/Editar/)
assert.match(page, /createLegacyPlanForAction/)
assert.match(actionListRoute, /qualityActionPlanId:\s*planId/)
assert.match(actionItemRoute, /export async function GET/)
assert.match(actionItemRoute, /qualityActionPlanId:\s*planId/)
assert.match(actionItemRoute, /nonConformityId:\s*null/)
assert.match(actionItemRoute, /origemPlano:\s*NonConformityActionPlanOrigin\.PLANO_AVULSO/)
assert.match(ncRoute, /nonConformityId:\s*id/)
assert.match(ncRoute, /origemPlano:\s*NonConformityActionPlanOrigin\.NAO_CONFORMIDADE/)
console.log('quality action plans hierarchy static checks passed')
