const fs = require('fs')
const assert = require('assert')
const read = (p) => fs.readFileSync(p, 'utf8')
const schema = read('prisma/schema.prisma')
const migration = read('prisma/migrations/202607070001_quality_action_plan_hierarchy/migration.sql')
const client = read('src/app/dashboard/sst/planos-de-acao/PlanosDeAcaoClient.tsx')
const detail = read('src/app/dashboard/sst/planos-de-acao/[planId]/PlanoAvulsoDetailClient.tsx')
const page = read('src/app/dashboard/sst/planos-de-acao/[planId]/page.tsx')
const menu = read('src/components/sst/SstModuleTabs.tsx')
const actionListRoute = read('src/app/api/sst/planos-de-acao/[planId]/acoes/route.ts')
const actionItemRoute = read('src/app/api/sst/planos-de-acao/[planId]/acoes/[actionId]/route.ts')
const ncRoute = read('src/app/api/sst/nao-conformidades/[id]/plano-de-acao/route.ts')
assert.match(schema, /model QualityActionPlan\s*\{/)
assert.match(schema, /model QualityActionPlanSequence\s*\{/)
assert.match(schema, /enum QualityActionPlanStatus\s*\{/)
assert.match(schema, /qualityActionPlanId\s+String\?/)
assert.match(schema, /nonConformityId\s+String\?/)
assert.match(migration, /GROUP BY `groupKey`, `numeroPlano`/, 'migração deve agrupar legados por referência')
assert.match(migration, /UPDATE `NonConformityActionItem` ai[\s\S]*qualityActionPlanId/, 'migração deve vincular ações ao plano pai')
assert.match(migration, /QualityActionPlanSequence[\s\S]*GREATEST/, 'migração deve avançar sequência para evitar número repetido')
assert.match(client, /\/api\/sst\/planos-de-acao/)
assert.match(client, /type PlanRow/)
assert.doesNotMatch(client, /type ActionRow/)
assert.match(client, /Planos de ação avulsos/)
assert.match(client, /Registrar plano de ação/)
assert.match(client, /Qtde de ações/)
assert.match(client, /% concluído/)
assert.match(client, /Exibir \/ Editar/)
assert.doesNotMatch(client, /<h1[^>]*>Ações do plano de ação/)
assert.match(menu, /Não conformidades/)
assert.match(menu, /Planos de ação avulsos/)
assert.doesNotMatch(menu, /Registrar plano de ação|Ações do plano de ação|Ações da não conformidade|Plano de ação \(submódulo\)/)
assert.match(detail, /planId/)
assert.match(detail, /\/api\/sst\/planos-de-acao\/\$\{planId\}/)
assert.match(detail, /\/api\/sst\/planos-de-acao\/\$\{planId\}\/acoes/)
assert.match(detail, /method: actionForm\.id \? 'PATCH' : 'POST'/)
assert.match(detail, /method: 'DELETE'/)
assert.match(detail, /Exibir\/Editar/)
assert.match(page, /createLegacyPlanForAction/)
assert.match(page, /redirect\(`\/dashboard\/sgi\/qualidade\/planos-de-acao\/\$\{targetPlanId\}`\)/)
assert.match(actionListRoute, /qualityActionPlanId:\s*planId/)
assert.match(actionListRoute, /origemPlano:\s*NonConformityActionPlanOrigin\.PLANO_AVULSO/)
assert.match(actionItemRoute, /qualityActionPlanId:\s*planId/)
assert.match(actionItemRoute, /findFirst\(\{ where: actionWhere\(planId, actionId\)/)
assert.doesNotMatch(actionItemRoute, /export \{ PATCH, DELETE \}/)
assert.match(ncRoute, /nonConformityId:\s*id/)
assert.match(ncRoute, /origemPlano:\s*NonConformityActionPlanOrigin\.NAO_CONFORMIDADE/)
console.log('quality action plans hierarchy static checks passed')
