const assert = require('node:assert')
const fs = require('node:fs')

const helper = fs.readFileSync('src/lib/solicitationCancellation.ts', 'utf8')
const policy = fs.readFileSync('src/lib/solicitationAccessPolicy.ts', 'utf8')
const cancelRoute = fs.readFileSync('src/app/api/solicitacoes/[id]/cancelar/route.ts', 'utf8')
const requestRoute = fs.readFileSync('src/app/api/solicitacoes/[id]/solicitar-cancelamento/route.ts', 'utf8')
const approveRoute = fs.readFileSync('src/app/api/solicitacoes/[id]/cancelamento/aprovar/route.ts', 'utf8')
const rejectRoute = fs.readFileSync('src/app/api/solicitacoes/[id]/cancelamento/recusar/route.ts', 'utf8')
const sentPage = fs.readFileSync('src/app/dashboard/solicitacoes/enviadas/page.tsx', 'utf8')
const lookupRoute = fs.readFileSync('src/app/api/solicitacoes/lookup/route.ts', 'utf8')
const detailModal = fs.readFileSync('src/components/solicitacoes/SolicitationDetailModal.tsx', 'utf8')
const schema = fs.readFileSync('prisma/schema.prisma', 'utf8')
const migration = fs.readFileSync('prisma/migrations/202605120001_add_solicitation_cancellation_audit/migration.sql', 'utf8')

assert.match(helper, /DIRECT_REQUESTER_CANCELLATION_STATUSES[\s\S]*ABERTA[\s\S]*AGUARDANDO_APROVACAO/, 'solicitante cancela direto status iniciais')
assert.match(helper, /!solicitation\.assumidaPorId/, 'solicitação assumida exige pedido pelo solicitante')
assert.match(cancelRoute, /action !== 'DIRECT'/, 'backend bloqueia cancelamento direto indevido com 403')
assert.match(requestRoute, /action !== 'REQUEST'/, 'backend valida quando solicitação de cancelamento é permitida')
assert.match(helper, /assertRequiredReason/, 'motivo vazio é validado')
assert.match(helper, /CLOSED_CANCELLATION_STATUSES[\s\S]*CONCLUIDA[\s\S]*CANCELADA/, 'status encerrados bloqueados')
assert.match(approveRoute, /cancelamentoStatus !== 'PENDENTE'/, 'aprovação exige pedido pendente')
assert.match(rejectRoute, /cancelamentoStatus !== 'PENDENTE'/, 'recusa exige pedido pendente')
assert.match(policy, /isViewerOnlyByPolicy\(ctx, solicitation\)\) return false/, 'visualizador não pode cancelar')
assert.match(approveRoute, /isViewerOnlyForSolicitation/, 'visualizador não pode aprovar')
assert.match(rejectRoute, /isViewerOnlyForSolicitation/, 'visualizador não pode recusar')
assert.match(policy, /ctx\.role === 'ADMIN'/, 'admin pode cancelar')
assert.match(policy, /canUserActAsFinalizerForCurrentStage/, 'finalizador pode cancelar conforme etapa')
assert.match(helper, /message = `Solicitação cancelada por[\s\S]*status: 'CANCELADA'/, 'histórico criado no cancelamento direto')
assert.match(helper, /CANCELAMENTO_SOLICITADO/, 'histórico criado no pedido de cancelamento')
assert.match(helper, /CANCELAMENTO_APROVADO[\s\S]*CANCELAMENTO_RECUSADO/, 'histórico criado na aprovação/recusa')
assert.match(sentPage, /resolveSentCancellationAction[\s\S]*Solicitar cancelamento/, 'enviadas resolve ação após lookup')
assert.match(sentPage, /disabled=\{sessionExpired \|\| !sessionData\?\.appUser\}/, 'frontend mantém botão Cancelar ativo sem selectedRow')
assert.match(sentPage, /Cancelar ou solicitar cancelamento por protocolo/, 'modal informa novo fluxo por protocolo')
assert.match(lookupRoute, /withModuleLevel\([\s\S]*'solicitacoes'[\s\S]*ModuleLevel\.NIVEL_1/, 'lookup exige módulo Solicitações')
assert.match(lookupRoute, /canViewSolicitation\(userAccess, solicitation\)/, 'lookup valida visibilidade')
assert.match(lookupRoute, /status: 404/, 'lookup retorna 404 para inexistente')
assert.match(lookupRoute, /status: 403/, 'lookup retorna 403 para sem visibilidade')
assert.match(detailModal, /Pedido de cancelamento pendente[\s\S]*Aprovar cancelamento[\s\S]*Recusar cancelamento/, 'detalhe exibe análise de cancelamento')
assert.match(schema, /cancelamentoStatus\s+String\?/, 'schema tem campos auditáveis')
assert.match(migration, /ADD COLUMN `cancelamentoStatus`/, 'migration cria campos de cancelamento')
