const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const root = path.resolve(__dirname, '..')
const read = (file) => fs.readFileSync(path.join(root, file), 'utf8')
const schema = read('prisma/schema.prisma')
const legacyRoute = read('src/app/api/sst/plano-de-acao/route.ts')
const planRoute = read('src/app/api/sst/planos-de-acao/route.ts')
const actionRoute = read('src/app/api/sst/planos-de-acao/[planId]/acoes/route.ts')
const client = read('src/app/dashboard/sst/planos-de-acao/PlanosDeAcaoClient.tsx')
assert.match(schema, /model NonConformityActionItem \{[\s\S]*descricao\s+String\s+@db\.LongText/, 'NonConformityActionItem.descricao deve ser LongText')
assert.match(legacyRoute, /if \(!descricao\) \{[\s\S]*Descrição é obrigatória\./, 'rota legada deve manter validação de descrição obrigatória')
assert.match(legacyRoute, /getValueTooLongMessage\(error\)[\s\S]*status: 400/, 'rota legada deve retornar erro claro para valor muito longo')
assert.match(actionRoute, /if \(!descricao\)[\s\S]*Descrição é obrigatória\./, 'ação dentro do plano deve validar descrição obrigatória')
assert.match(planRoute, /Título é obrigatório\./, 'plano pai deve validar título obrigatório')
assert.match(client, /setCreateError\(e\?\.message \|\| 'Erro ao registrar plano\.'\)/, 'front deve exibir mensagem de erro retornada pela API no modal')
assert.match(client, /<button type="submit" disabled=\{creating\} className="app-button-primary">/, 'botão Registrar deve continuar desabilitado durante envio')
console.log('sst action plan long description regression ok')
