const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const root = path.resolve(__dirname, '..')
const read = (file) => fs.readFileSync(path.join(root, file), 'utf8')
const client = read('src/app/dashboard/sst/planos-de-acao/PlanosDeAcaoClient.tsx')
const responsaveisRoute = read('src/app/api/sst/plano-de-acao/responsaveis/route.ts')
assert.match(client, /Registrar plano de ação/, 'modal deve registrar o plano pai')
assert.match(client, /Field label="Título \*"/, 'plano pai deve ter título obrigatório')
assert.match(client, /Field label="Responsável"/, 'plano pai deve permitir responsável textual')
assert.doesNotMatch(client, /Field label="Fim previsto"/, 'modal inicial do plano pai não deve pedir prazo final previsto')
assert.match(client, /responsavelNome/, 'formulário deve enviar nome do responsável no body do POST')
assert.match(client, /fetch\('\/api\/sst\/planos-de-acao'/, 'formulário deve criar plano pai na nova API')
assert.match(client, /<button type="submit" disabled=\{creating\} className="app-button-primary">/, 'botão Registrar deve continuar desabilitado durante creating')
assert.match(responsaveisRoute, /hasMinLevel\(level, ModuleLevel\.NIVEL_1\)[\s\S]*FEATURE_KEYS\.SST\.PLANO_DE_ACAO, Action\.VIEW[\s\S]*select: \{[\s\S]*id: true,[\s\S]*fullName: true,[\s\S]*email: true/, 'endpoint de responsáveis deve exigir SST e retornar apenas dados mínimos')
console.log('sst action plan modal layout responsavel regression ok')
