ALTER TABLE `Solicitation`
  MODIFY `status` ENUM(
    'ABERTA',
    'EM_ATENDIMENTO',
    'AGUARDANDO_APROVACAO',
    'AGUARDANDO_TERMO',
    'AGUARDANDO_AVALIACAO_GESTOR',
    'CONCLUIDA',
    'CANCELADA'
  ) NOT NULL DEFAULT 'ABERTA';